on:
  push:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - run: |
          dart pub global activate --source path spec/packages/spec_cli
      - run: |
          spec --coverage --ci
