on:
  push:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get      
      #- uses: subosito/flutter-action@v2
      #  with:
      #    flutter-version: ${{ env.FLUTTER_VERSION }}
      #    channel: ${{ env.FLUTTER_CHANNEL }}
      #    cache: true
      - run: |
          dart pub global activate spec_cli
      - run: |
          spec --coverage --ci
